"""initial schema

Revision ID: 4e99108b6325
Revises: 
Create Date: 2026-05-07 18:50:14.376291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e99108b6325'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benefactor_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('handle', sa.String(), nullable=False),
    sa.Column('pass_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('benefactor_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_benefactor_accounts_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_benefactor_accounts_handle'), ['handle'], unique=True)

    op.create_table('causes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index')
    )
    op.create_table('organizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mission_statement', sa.Text(), nullable=True),
    sa.Column('website_link', sa.String(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('date_approved', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('initiatives',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('cause_id', sa.String(), nullable=False),
    sa.Column('cycle_num', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('emoji', sa.String(), nullable=True),
    sa.Column('proposed_by', sa.String(), nullable=False),
    sa.Column('proposer_benefactor_id', sa.Integer(), nullable=True),
    sa.Column('proposer_org_id', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('ebx_committed', sa.Integer(), nullable=False),
    sa.Column('pool_value', sa.Integer(), nullable=False),
    sa.Column('election_open', sa.DateTime(), nullable=True),
    sa.Column('election_close', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('winning_org_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cause_id'], ['causes.id'], ),
    sa.ForeignKeyConstraint(['proposer_benefactor_id'], ['benefactor_accounts.id'], ),
    sa.ForeignKeyConstraint(['proposer_org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['winning_org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memberships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('benefactor_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['benefactor_id'], ['benefactor_accounts.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('benefactor_id', 'organization_id', name='uq_member_org')
    )
    op.create_table('organization_causes',
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('cause_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cause_id'], ['causes.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('organization_id', 'cause_id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('benefactor_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['benefactor_id'], ['benefactor_accounts.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contributions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('benefactor_id', sa.Integer(), nullable=False),
    sa.Column('initiative_id', sa.String(), nullable=False),
    sa.Column('amount_ebx', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['benefactor_id'], ['benefactor_accounts.id'], ),
    sa.ForeignKeyConstraint(['initiative_id'], ['initiatives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('missions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('initiative_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('community_members', sa.Integer(), nullable=False),
    sa.Column('credit_value', sa.Float(), nullable=False),
    sa.Column('budget', sa.Integer(), nullable=False),
    sa.Column('spent', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['initiative_id'], ['initiatives.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit_coins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.String(), nullable=False),
    sa.Column('amount_ebx', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('redeemed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['benefactor_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mission_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mission_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('author_type', sa.String(), nullable=False),
    sa.Column('author_label', sa.String(), nullable=True),
    sa.Column('benefactor_author_id', sa.Integer(), nullable=True),
    sa.Column('org_author_id', sa.String(), nullable=True),
    sa.Column('cause_id', sa.String(), nullable=True),
    sa.Column('initiative_id', sa.String(), nullable=True),
    sa.Column('mission_id', sa.String(), nullable=True),
    sa.Column('opinion_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['benefactor_author_id'], ['benefactor_accounts.id'], ),
    sa.ForeignKeyConstraint(['cause_id'], ['causes.id'], ),
    sa.ForeignKeyConstraint(['initiative_id'], ['initiatives.id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.ForeignKeyConstraint(['org_author_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('mission_metrics')
    op.drop_table('credit_coins')
    op.drop_table('missions')
    op.drop_table('contributions')
    op.drop_table('reviews')
    op.drop_table('organization_causes')
    op.drop_table('memberships')
    op.drop_table('initiatives')
    op.drop_table('organizations')
    op.drop_table('causes')
    with op.batch_alter_table('benefactor_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_benefactor_accounts_handle'))
        batch_op.drop_index(batch_op.f('ix_benefactor_accounts_email'))

    op.drop_table('benefactor_accounts')
    # ### end Alembic commands ###
