"""Adding account generation logic

Revision ID: 6234942e38f2
Revises: 4e99108b6325
Create Date: 2026-05-12 12:35:22.042469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6234942e38f2'
down_revision = '4e99108b6325'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
