"""jun15 v2 mission-centric rebuild (CUTOVER migration)

Revision ID: a9f2c1b4d7e3
Revises: f4a9c1d2e6b3
Create Date: 2026-06-15

============================  READ BEFORE RUNNING  ============================
This is the v1 -> v2 CUTOVER. It DROPS every v1 table and REBUILDS the schema
mission-centric. It does NOT preserve data — back up earthbucks.db first, and
only run it once models.py / crud.py / routers have been swapped to v2. Running
it against the live v1 app will break the app until the rewire lands.

Exact delta vs v1 (head f4a9c1d2e6b3)
-------------------------------------
NEW tables:      missions(restructured), votes_p1, votes_p2, mission_candidacies,
                 pools, queries, transactions
DROPPED tables:  contributions, votes, vote_events, org_registrations,
                 organization_causes  (vote_events folded into transactions)
RENAMED cols:    benefactor_id -> ben_id, initiative_id -> tiv_id (everywhere),
                 watched_initiative_ids -> watched_tiv_ids
RESHAPED:        initiatives loses election/pool/winning_org cols, gains
                 mission_id + approved; missions becomes the spine (cause_id,
                 cycle_num, current_phase, winning_tiv_id, winning_org_id);
                 posts switch to category + helpful/neutral/harmful; benefactor
                 gains role (employee category); credit_coins gain value.
==============================================================================
"""
from alembic import op
import sqlalchemy as sa

revision = "a9f2c1b4d7e3"
down_revision = "f4a9c1d2e6b3"
branch_labels = None
depends_on = None


# v1 tables to drop, child-before-parent so FKs never block the drop.
_V1_TABLES = [
    "post_votes", "vote_events", "votes", "contributions", "credit_coins",
    "org_registrations", "organization_causes", "memberships", "posts",
    "missions", "initiatives", "organizations", "benefactor_accounts", "causes",
]

# v2 tables in reverse create order, for a clean downgrade.
_V2_TABLES = [
    "post_votes", "votes_p2", "transactions", "posts", "mission_candidacies",
    "memberships", "votes_p1", "queries", "pools", "organizations",
    "credit_coins", "missions", "initiatives", "causes", "benefactor_accounts",
]


def upgrade() -> None:
    # --- drop the entire v1 schema ---
    for tbl in _V1_TABLES:
        op.drop_table(tbl)

    # --- build the v2 schema (autogenerated from the v2 metadata) ---
    op.create_table(
        "benefactor_accounts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("handle", sa.String(), nullable=False),
        sa.Column("pass_hash", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("vvv", sa.Boolean(), nullable=False),
        sa.Column("watched_tiv_ids", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_benefactor_accounts_email"), "benefactor_accounts", ["email"], unique=True)
    op.create_index(op.f("ix_benefactor_accounts_handle"), "benefactor_accounts", ["handle"], unique=True)

    op.create_table(
        "causes",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("color", sa.String(), nullable=False),
        sa.Column("emoji", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("index"),
    )

    op.create_table(
        "initiatives",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("emoji", sa.String(), nullable=True),
        sa.Column("cause_id", sa.String(), nullable=False),
        sa.Column("mission_id", sa.String(), nullable=True),
        sa.Column("proposer_ben_id", sa.Integer(), nullable=True),
        sa.Column("proposer_org_id", sa.String(), nullable=True),
        sa.Column("proposed_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("rating_avg", sa.Float(), nullable=False),
        sa.Column("rating_count", sa.Integer(), nullable=False),
        sa.Column("logo_url", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("approved", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["cause_id"], ["causes.id"]),
        sa.ForeignKeyConstraint(["mission_id"], ["missions.id"]),
        sa.ForeignKeyConstraint(["proposer_ben_id"], ["benefactor_accounts.id"]),
        sa.ForeignKeyConstraint(["proposer_org_id"], ["organizations.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "missions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("cause_id", sa.String(), nullable=False),
        sa.Column("cycle_num", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("current_phase", sa.String(), nullable=False),
        sa.Column("winning_tiv_id", sa.String(), nullable=True),
        sa.Column("winning_org_id", sa.String(), nullable=True),
        sa.Column("budget", sa.Integer(), nullable=False),
        sa.Column("spent", sa.Integer(), nullable=False),
        sa.Column("credit_value", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.ForeignKeyConstraint(["cause_id"], ["causes.id"]),
        sa.ForeignKeyConstraint(["winning_org_id"], ["organizations.id"]),
        sa.ForeignKeyConstraint(["winning_tiv_id"], ["initiatives.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cause_id", "cycle_num", name="uq_mission_cause_cycle"),
    )

    op.create_table(
        "credit_coins",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("mission_id", sa.String(), nullable=False),
        sa.Column("amount_ebx", sa.Integer(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("issued_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("redeemed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["mission_id"], ["missions.id"]),
        sa.ForeignKeyConstraint(["owner_id"], ["benefactor_accounts.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "organizations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("website_link", sa.String(), nullable=True),
        sa.Column("founded_year", sa.Integer(), nullable=True),
        sa.Column("founding_member_id", sa.Integer(), nullable=True),
        sa.Column("joined_at", sa.DateTime(), nullable=True),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("logo_url", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["founding_member_id"], ["benefactor_accounts.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "pools",
        sa.Column("mission_id", sa.String(), nullable=False),
        sa.Column("phase1_total_ebx", sa.Integer(), nullable=False),
        sa.Column("phase2_total_ebx", sa.Integer(), nullable=False),
        sa.Column("pool_from_winners", sa.Integer(), nullable=False),
        sa.Column("pool_from_losers", sa.Integer(), nullable=False),
        sa.Column("total_locked", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.ForeignKeyConstraint(["mission_id"], ["missions.id"]),
        sa.PrimaryKeyConstraint("mission_id"),
    )

    op.create_table(
        "queries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("entity", sa.String(), nullable=True),
        sa.Column("filters", sa.Text(), nullable=True),
        sa.Column("sort", sa.String(), nullable=True),
        sa.Column("sql", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("shared", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("last_run_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["created_by_id"], ["benefactor_accounts.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "votes_p1",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ben_id", sa.Integer(), nullable=False),
        sa.Column("mission_id", sa.String(), nullable=False),
        sa.Column("tiv_id", sa.String(), nullable=False),
        sa.Column("share", sa.Float(), nullable=False),
        sa.Column("ebx_committed", sa.Integer(), nullable=False),
        sa.Column("valence", sa.String(), nullable=False),
        sa.Column("committed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.ForeignKeyConstraint(["ben_id"], ["benefactor_accounts.id"]),
        sa.ForeignKeyConstraint(["mission_id"], ["missions.id"]),
        sa.ForeignKeyConstraint(["tiv_id"], ["initiatives.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ben_id", "tiv_id", name="uq_votep1_ben_tiv"),
    )

    op.create_table(
        "memberships",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ben_id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("joined_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.ForeignKeyConstraint(["ben_id"], ["benefactor_accounts.id"]),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ben_id", "org_id", name="uq_member_org"),
    )

    op.create_table(
        "mission_candidacies",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("mission_id", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("mission_statement", sa.Text(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("submitted_by_id", sa.Integer(), nullable=True),
        sa.Column("approved_by_id", sa.Integer(), nullable=True),
        sa.Column("p2_vote_tally", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.ForeignKeyConstraint(["approved_by_id"], ["benefactor_accounts.id"]),
        sa.ForeignKeyConstraint(["mission_id"], ["missions.id"]),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"]),
        sa.ForeignKeyConstraint(["submitted_by_id"], ["benefactor_accounts.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mission_id", "org_id", name="uq_candidacy_mission_org"),
    )

    op.create_table(
        "posts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("author_type", sa.String(), nullable=False),
        sa.Column("ben_author_id", sa.Integer(), nullable=True),
        sa.Column("org_author_id", sa.String(), nullable=True),
        sa.Column("mission_id", sa.String(), nullable=True),
        sa.Column("tiv_id", sa.String(), nullable=True),
        sa.Column("cause_id", sa.String(), nullable=True),
        sa.Column("helpful_count", sa.Integer(), nullable=False),
        sa.Column("neutral_count", sa.Integer(), nullable=False),
        sa.Column("harmful_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.ForeignKeyConstraint(["ben_author_id"], ["benefactor_accounts.id"]),
        sa.ForeignKeyConstraint(["cause_id"], ["causes.id"]),
        sa.ForeignKeyConstraint(["mission_id"], ["missions.id"]),
        sa.ForeignKeyConstraint(["org_author_id"], ["organizations.id"]),
        sa.ForeignKeyConstraint(["tiv_id"], ["initiatives.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("ben_id", sa.Integer(), nullable=True),
        sa.Column("mission_id", sa.String(), nullable=True),
        sa.Column("phase", sa.String(), nullable=True),
        sa.Column("action", sa.String(), nullable=True),
        sa.Column("target", sa.String(), nullable=True),
        sa.Column("old_value", sa.String(), nullable=True),
        sa.Column("new_value", sa.String(), nullable=True),
        sa.Column("bucket", sa.String(), nullable=True),
        sa.Column("counterparty_org_id", sa.String(), nullable=True),
        sa.Column("amount_ebx", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.ForeignKeyConstraint(["ben_id"], ["benefactor_accounts.id"]),
        sa.ForeignKeyConstraint(["counterparty_org_id"], ["organizations.id"]),
        sa.ForeignKeyConstraint(["mission_id"], ["missions.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "votes_p2",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ben_id", sa.Integer(), nullable=False),
        sa.Column("mission_id", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("votes", sa.Integer(), nullable=False),
        sa.Column("ebx_spent", sa.Integer(), nullable=False),
        sa.Column("valence", sa.String(), nullable=False),
        sa.Column("committed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.ForeignKeyConstraint(["ben_id"], ["benefactor_accounts.id"]),
        sa.ForeignKeyConstraint(["mission_id"], ["missions.id"]),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ben_id", "mission_id", name="uq_votep2_ben_mission"),
    )

    op.create_table(
        "post_votes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("post_id", sa.String(), nullable=False),
        sa.Column("ben_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.ForeignKeyConstraint(["ben_id"], ["benefactor_accounts.id"]),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("post_id", "ben_id", name="uq_post_vote_ben"),
    )


def downgrade() -> None:
    # Drops the v2 schema. Full v1 restoration is NOT provided here — restore
    # earthbucks.db from backup or `git checkout` the prior DB to go back.
    for tbl in _V2_TABLES:
        op.drop_table(tbl)
