"""Add votes table

Revision ID: af0d14f1a4e8
Revises: 6234942e38f2
Create Date: 2026-05-13 19:09:12.848521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af0d14f1a4e8'
down_revision = '6234942e38f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('benefactor_id', sa.Integer(), nullable=False),
    sa.Column('initiative_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['benefactor_id'], ['benefactor_accounts.id'], ),
    sa.ForeignKeyConstraint(['initiative_id'], ['initiatives.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('benefactor_id', 'initiative_id', name='uq_vote_benefactor_initiative')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    # ### end Alembic commands ###
